In [158]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
df = pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [159]:
df = df.drop(('Species'), axis=1)
df


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [160]:
# if we do not specify the attributes collecton by default the attribute selection measeure is gene index

In [161]:
model= DecisionTreeClassifier(criterion='gini')


In [162]:
gini_impurities = ()

In [163]:
df.shape

(150, 5)

In [164]:
df.shape[1]

5

In [165]:
# Reshape command in numpy is used to reshape our numpy array

In [166]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print('ORIGINAL SHAPE',arr.shape)

reshaped_arr= arr.reshape(-1,1)
print('RESHAPED SHAPE',reshaped_arr.shape)

ORIGINAL SHAPE (6,)
RESHAPED SHAPE (6, 1)


In [167]:
# When we Reshadding the array then the number of rows and columns shall be a factor oftotal number of elements present in the array....

In [168]:
reshaped_arr = arr.reshape(2,3)
print("reshaped array shape", reshaped_arr.shape)
print(reshaped_arr)

reshaped array shape (2, 3)
[[1 2 3]
 [4 5 6]]


In [169]:
reshaped_arr = arr.reshape(1,6)
print("reshaped array shape", reshaped_arr.shape)
print(reshaped_arr)

reshaped array shape (1, 6)
[[1 2 3 4 5 6]]


In [170]:
reshaped_arr = arr.reshape(6,1)
print("reshaped array shape", reshaped_arr.shape)
print(reshaped_arr)

reshaped array shape (6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [171]:
reshaped_arr[:,0]

array([1, 2, 3, 4, 5, 6])

In [175]:
#array([1,4])
#for i in range(df.shape[i]):
 # model = model.fit(df.iloc[:,i].values.reshape(-1,1)),y
  #prob = model.predict_proba(df.iloc[:,i].values.reshape(-1,1))
 # gini_impurities[i] = 1- (prob[:,0]**2 + prob[:,2]**2).sum()

In [177]:
import numpy as np

np.array([1,4])
for i in range(df.shape[1]):
  model = model.fit(df.iloc[:,i].values.reshape(-1,1),y)
  prob = model.predict_proba(df.iloc[:,i].values.reshape(-1,1))
  gini_impurities[i] = 1- (prob[:,0]**2 + prob[:,1]**2).sum()

TypeError: DecisionTreeClassifier.fit() missing 1 required positional argument: 'y'

In [174]:
best_feature = min(gini_impurities, key=gini_impurities.get)
print(f"Best feature: (best_feature)")

AttributeError: 'tuple' object has no attribute 'get'

In [ ]:
import matplotlib.pyplot as plt
from sklearn.tree import plot_tree
plt.figure(figsize=(15,10))
plot_tree(model, filled=True)
plt.tittle('Original Decision Tree')
plt.show()

In [178]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
df = pd.read_csv('User_Data.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]