In [5]:
import numpy as np
a = np.zeros(3)
a


array([0., 0., 0.])

In [4]:
type(a)

numpy.ndarray

In [7]:
type(a[0])

numpy.float64

In [9]:
a = np.zeros(3,dtype=int)
a


array([0, 0, 0])

In [13]:
z = np.zeros(10)
z.shape

(10,)

In [14]:
z.shape = (10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [15]:
z = np.zeros(4)
z.shape = (2,2)
z

array([[0., 0.],
       [0., 0.]])

In [16]:
z = np.empty(3)
z

array([0., 0., 0.])

In [17]:
z = np.linspace(2,4,5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [18]:
z = np.linspace(3,42,28)
z

array([ 3.        ,  4.44444444,  5.88888889,  7.33333333,  8.77777778,
       10.22222222, 11.66666667, 13.11111111, 14.55555556, 16.        ,
       17.44444444, 18.88888889, 20.33333333, 21.77777778, 23.22222222,
       24.66666667, 26.11111111, 27.55555556, 29.        , 30.44444444,
       31.88888889, 33.33333333, 34.77777778, 36.22222222, 37.66666667,
       39.11111111, 40.55555556, 42.        ])

In [19]:
z = np.identity(2)
z

array([[1., 0.],
       [0., 1.]])

In [20]:
z = np.array([10,20])
z

array([10, 20])

In [21]:
type(z)

numpy.ndarray

In [22]:
z = np.array([[1,2],[3,4]])
z

array([[1, 2],
       [3, 4]])

In [23]:
z = np.linspace(1,2,5)
z

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [24]:
z[0]

1.0

In [25]:
z[0:2]

array([1.  , 1.25])

In [26]:
z[-1]

2.0

In [32]:
z = np.array([[1,2],[3,4]])
z
z[0,:]

array([1, 2])

In [33]:
z[0,0]

1

In [35]:
a = np.array([[1,3,4],[3,2,1],[5,3,2]])
a

array([[1, 3, 4],
       [3, 2, 1],
       [5, 3, 2]])

In [37]:
a[:,1]

array([3, 2, 3])

In [43]:
z = np.linspace(2,4,5)
indices= np.array([0,2,3])
z[indices]

array([2. , 3. , 3.5])

In [46]:
d = np.array([0,1,1,0,0,4], dtype = bool)
d

array([False,  True,  True, False, False,  True])

In [50]:
a = np.array([1,2,5])
a


array([1, 2, 5])

In [48]:
a.sort()
a

array([1, 2, 5])

In [49]:
# the changes will be reflected in the original error as well

In [52]:
a=np.array([12,43,23,12,321,43,21,])
a.sum()

475

In [53]:
a.max()

321

In [54]:
a.sort()
a.argmax()

6

In [55]:
a=np.array([12,43,23,12,321,43,21,])
a.min()

12

In [57]:
a=np.array([12,43,23,12,321,43,21,])
a.sort()
a.argmin()

0

In [58]:
a.cumsum()

array([ 12,  24,  45,  68, 111, 154, 475])

In [60]:
a.cumprod()

array([         12,         144,        3024,       69552,     2990736,
         128601648, 41281129008])

In [61]:
a.var()

10823.551020408164

In [65]:
a.searchsorted(2.6)

0

In [66]:
z = np.linspace(2,4,5)

In [67]:
z.searchsorted(2.6)

2

In [70]:
b = np.array([4,3,2,1])

In [71]:
np.sum(b)

10

In [74]:
np.mean(b)

2.5

In [75]:
np.sort(b)

array([1, 2, 3, 4])

In [76]:
np.max(b)

4

In [77]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [78]:
a+b

array([ 6,  8, 10, 12])

In [79]:
a*b

array([ 5, 12, 21, 32])

In [80]:
a*10

array([10, 20, 30, 40])

In [93]:
a = np.array([[1,3,4]])
b = np.array([[6,7,8]])

In [84]:
a+b

array([[ 7, 10, 12]])

In [95]:
a = np.array([[1,3]])
b = np.array([[6,7]])

In [86]:
a+b

array([[ 7, 10]])

In [96]:
a = np.array([[1,3]])
b = np.array([[6],[7]])
a@b

array([[27]])

In [97]:
a*5

array([[ 5, 15]])

In [98]:
a[0]

array([1, 3])

In [101]:
z!=a

ValueError: operands could not be broadcast together with shapes (5,) (1,2) 

In [100]:
z[z>3]

array([3.5, 4. ])